application: goandgiveuk
version: 2
runtime: go
api_version: go1

handlers:

# Other webpages are also handled by the Go application.
- url: /(.*\.html)
  script: app/_go_app

- url: /(.*\.htm)
  script: app/_go_app

# Signup handler is through the Go application.
- url: /signup
  script: app/_go_app

# Contact handler is through the Go application.
- url: /contactSubmission
  script: app/_go_app

# robots.txt
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

# favicon.ico
- url: /favicon.ico
  mime_type: image/x-icon
  static_files: static/favicon.ico
  upload: static/favicon.ico

# All URLs beginning with /css are treated as paths to static files in
# the css/ directory.
- url: /css
  static_dir: css

- url: /css/ie
  static_dir: css/ie

- url: /js
  static_dir: js

- url: /fonts/(.*\.woff)
  static_files: fonts/\1
  upload: fonts/(.*\.woff)
  mime_type: application/font-woff

- url: /fonts/(.*\.woff2)
  static_files: fonts/\1
  upload: fonts/(.*\.woff2)
  mime_type: application/font-woff2

- url: /fonts/(.*\.svg)
  static_files: fonts/\1
  upload: fonts/(.*\.svg)
  mime_type: image/svg+xml

- url: /fonts/(.*\.eot)
  static_files: fonts/\1
  upload: fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /fonts/(.*\.ttf)
  static_files: fonts/\1
  upload: fonts/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /fonts/(.*\.otf)
  static_files: fonts/\1
  upload: fonts/(.*\.otf)
  mime_type: application/x-font-otf

- url: /images
  static_dir: images

  # Main handler for the app.
- url: /
  script: app/_go_app