application: goandgiveuk
version: 1
runtime: go
api_version: go1

handlers:
# Main handler for the app.
- url: /
  script: app/_go_app
  
# Other webpages are also handled by the Go application.
- url: /(.*\.html)
  script: _go_app

# Signup handler is through the Go application.
- url: /signup
  script: app/_go_app

# Contact handler is through the Go application.
- url: /contactSubmission
  script: app/_go_app

# favicon.ico
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

# robots.txt
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

# All URLs beginning with /css are treated as paths to static files in
# the css/ directory.
- url: /css
  static_dir: css

- url: /css/ie
  static_dir: css/ie

- url: /js
  static_dir: js

- url: /fonts/(.*\.woff)
  static_files: fonts/\1
  upload: fonts/(.*\.woff)
  mime_type: application/font-woff

- url: /fonts/(.*\.woff2)
  static_files: fonts/\1
  upload: fonts/(.*\.woff2)
  mime_type: application/font-woff2

- url: /fonts/(.*\.svg)
  static_files: fonts/\1
  upload: fonts/(.*\.svg)
  mime_type: image/svg+xml

- url: /fonts/(.*\.eot)
  static_files: fonts/\1
  upload: fonts/(.*\.eot)
  mime_type: application/vnd.ms-fontobject

- url: /fonts/(.*\.ttf)
  static_files: fonts/\1
  upload: fonts/(.*\.ttf)
  mime_type: application/x-font-ttf

- url: /fonts/(.*\.otf)
  static_files: fonts/\1
  upload: fonts/(.*\.otf)
  mime_type: application/x-font-otf

- url: /images
  static_dir: images

- url: /sass
  static_dir: sass
  
- url: /sass/ie
  static_dir: sass/ie